// Language configurations for the editor
export const LANGUAGES = {
  javascript: {
    id: 'javascript',
    label: 'JavaScript',
    monacoId: 'javascript',
    extension: '.js',
    icon: '🟨',
    defaultCode: '// JavaScript\nconsole.log("Hello, World!");\n',
    runLocally: true,
  },
  python: {
    id: 'python',
    label: 'Python',
    monacoId: 'python',
    extension: '.py',
    icon: '🐍',
    defaultCode: '# Python\nprint("Hello, World!")\n',
    runLocally: false,
  },
  cpp: {
    id: 'cpp',
    label: 'C++',
    monacoId: 'cpp',
    extension: '.cpp',
    icon: '⚙️',
    defaultCode: '#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Hello, World!" << endl;\n    return 0;\n}\n',
    runLocally: false,
  },
  java: {
    id: 'java',
    label: 'Java',
    monacoId: 'java',
    extension: '.java',
    icon: '☕',
    defaultCode: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}\n',
    runLocally: false,
  },
  typescript: {
    id: 'typescript',
    label: 'TypeScript',
    monacoId: 'typescript',
    extension: '.ts',
    icon: '🔷',
    defaultCode: '// TypeScript\nconst greeting: string = "Hello, World!";\nconsole.log(greeting);\n',
    runLocally: false,
  },
  go: {
    id: 'go',
    label: 'Go',
    monacoId: 'go',
    extension: '.go',
    icon: '🐹',
    defaultCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, World!")\n}\n',
    runLocally: false,
  },
  rust: {
    id: 'rust',
    label: 'Rust',
    monacoId: 'rust',
    extension: '.rs',
    icon: '🦀',
    defaultCode: 'fn main() {\n    println!("Hello, World!");\n}\n',
    runLocally: false,
  },
  ruby: {
    id: 'ruby',
    label: 'Ruby',
    monacoId: 'ruby',
    extension: '.rb',
    icon: '💎',
    defaultCode: '# Ruby\nputs "Hello, World!"\n',
    runLocally: false,
  },
  php: {
    id: 'php',
    label: 'PHP',
    monacoId: 'php',
    extension: '.php',
    icon: '🐘',
    defaultCode: '<?php\necho "Hello, World!";\n?>\n',
    runLocally: false,
  },
  csharp: {
    id: 'csharp',
    label: 'C#',
    monacoId: 'csharp',
    extension: '.cs',
    icon: '🟪',
    defaultCode: 'using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine("Hello, World!");\n    }\n}\n',
    runLocally: false,
  },
};

export const LANGUAGE_LIST = Object.values(LANGUAGES);

export const KEYBOARD_SHORTCUTS = {
  run: { key: 'Enter', ctrlKey: true, label: 'Ctrl+Enter' },
  save: { key: 's', ctrlKey: true, label: 'Ctrl+S' },
  export: { key: 'e', ctrlKey: true, label: 'Ctrl+E' },
  newTab: { key: 'n', ctrlKey: true, label: 'Ctrl+N' },
  closeTab: { key: 'w', ctrlKey: true, label: 'Ctrl+W' },
  toggleOutput: { key: '`', ctrlKey: true, label: 'Ctrl+`' },
};
